language: rust
os: linux
dist: bionic
sudo: require

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  - LIBVIRT=2.5.0  EXT=xz
  - LIBVIRT=3.10.0  EXT=xz
  - LIBVIRT=4.10.0  EXT=xz
  - LIBVIRT=5.5.0  EXT=xz

install:
  - sudo apt-get -qqy build-dep libvirt
  - sudo apt-get -qqy install curl qemu-system-x86 sasl2-bin
  - sudo mkdir -p /usr/src && sudo chown $(id -u) /usr/src
  - curl -O -s https://libvirt.org/sources/libvirt-${LIBVIRT}.tar.${EXT}
  - tar -C /usr/src -xf libvirt-${LIBVIRT}.tar.${EXT}
  - pushd /usr/src/libvirt-${LIBVIRT}
  - |
        ./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc \
                    --without-polkit \
                    --without-esx --without-vbox --without-xen --without-libxl \
                    --with-qemu --with-lxc
  - make
  - sudo make install
  - popd
  - sudo cp tests/libvirtd.sasl /etc/sasl2/libvirt.conf
  - sudo libvirtd -d -l -f tests/libvirtd.conf
  - sudo virtlogd -d || true
  - sudo chmod a+rwx /var/run/libvirt/libvirt-sock*
  - echo "pass" | sudo saslpasswd2 -p -a libvirt user

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt -v -- --check;
  - cargo test --verbose
  # Due to an issue fixed in master we should not consider running
  # integration tests in parallel.
  # see: https://www.redhat.com/archives/libvir-list/2019-July/msg00287.html
  - cargo test --verbose -- --ignored --test-threads=1
