[package]
name = "virt"
version = "0.2.11"
authors = ["Sahid Orentino Ferdjaoui <sahid.ferdjaoui@libremel.fr>",]
license = "LGPL-2.1"
readme = "README.md"
description = "Rust bindings to the libvirt C library"
documentation = "http://docs.rs/virt"
keywords = ["libvirt", "virtualization", "KVM", "QEMU", "Xen",]
categories = ["api-bindings", "external-ffi-bindings", "emulators",]
repository = "http://libvirt.org/git/?p=libvirt-rust.git;a=summary"
homepage  = "https://libvirt.org/"

[dependencies]
libc = "0.2.0"